name: Signed artifact deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Github environment to use'
        default: deployment_ossrh
        required: false
        type: string
      repository:
        description: 'Maven repository (distribution management) for deploying the artifacts'
        default: ossrh
        required: false
        type: string
      profile:
        description: 'Deployment profile'
        default: deployment-ossrh
        required: false
        type: string
    secrets:
      USERNAME:
        description: 'Username for deploying'
        required: true
      PASSWORD:
        description: 'Password for deploying'
        required: true
      GPG_PRIVATE_KEY:
        description: 'Private key for signing'
        required: true
      GPG_PASSPHRASE:
        description: 'Passphrase for signing'
        required: true

jobs:
  deploy:
    name: Deploy
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
        cache: 'maven'
        server-id: ${{ inputs.repository }}
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Build
      run: mvn clean package -B -P ${{ inputs.profile }} -DskipTests
    - name: Deploy
      run: mvn deploy -B -P ${{ inputs.profile }} -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
