name: Pypi deployment

on:
  workflow_call:
    inputs:
      environment:
        description: 'Github environment to use'
        default: deployment_pypi
        required: false
        type: string
    secrets:
      username:
        description: 'Username for deploying'
        required: true
      password:
        description: 'Password for deploying'
        required: true

jobs:
  deploy:
    name: Deploy
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build distribution
      run: python setup.py sdist bdist_wheel
    - name: Deploy
      run: twine upload -r pypi dist/*
      env:
        TWINE_USERNAME: ${{ secrets.username }}
        TWINE_PASSWORD: ${{ secrets.password }}
